import '@styles/globals.css'
import { inter } from '../fonts/fonts'
export const metadata = {
  title: 'Cudium-Dashboard',
  description: 'Generated by Cudium Engineering Team',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>{children}</body>
    </html>
  )
}
